# Generated by Django 4.0.6 on 2022-12-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
