# Generated by Django 4.0.6 on 2022-12-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='contacts',
            field=models.ManyToManyField(related_name='tags', to='contacts.contact'),
        ),
    ]
