# Generated by Django 4.0.6 on 2023-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('team', 'Team'), ('review', 'Review'), ('extras', 'Extras')], default='extras', max_length=55),
        ),
    ]
