# Generated by Django 4.0.6 on 2022-09-12 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='director_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='manager_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
